//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "comments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub post_id: i64,
    pub user_id: i64,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "post_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub posts: HasOne<super::posts::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
