//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::comment::Entity as Comment;
pub use super::post::Entity as Post;
pub use super::post_tag::Entity as PostTag;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
