//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub username: String,
    pub created_at: DateTime,
    #[sea_orm(has_many)]
    pub comments: HasMany<super::comments::Entity>,
    #[sea_orm(has_many)]
    pub posts: HasMany<super::posts::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
