[package]
name = "sqlx-basics"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
sqlx = { version = "0.8.6", features = ["postgres", "mysql", "sqlite", "runtime-tokio", "macros"] }
tokio = { version = "1.47.1", features = ["full"] }
